task: paevakaja_et_instr_gemma
dataset_path: TalTechNLP/paevakaja_speakers
dataset_name: null
output_type: generate_until
generation_kwargs:
  until:
    - "\n\n\n\n\n"
  do_sample: false
  temperature: 0.0
training_split: null
validation_split: null
test_split: train
fewshot_split: null
doc_to_text: "Sa oled ekspert Eesti avaliku elu tegelaste alal. Sulle antakse uudiste- või vestlussaate automaatne transkriptsioon, koos kõneleja koodidega. Proovi arvata, millised isikud saates kõnelevad, nii reporterid kui ka intervjueeritavad. Väljasta tulemus JSONi abil. JSON formaadi näide: ['nimi1', 'nimi2'].  Ära liialt riski, meile on täpsus olulisem kui saagis. Nimed võivad olla valesti transkribeeritud, kasuta oma taustateadmisi, et neid vajadusel korrigeerida. KINDLASTI ANNA VASTUSEKS AINULT ÜKS JSON LIST JA MITTE MIDAGI MUUD. Uudistesaate transkriptsioon: {{text}}"
doc_to_target: speakers
target_delimiter: " "
should_decontaminate: false
doc_to_decontamination_query: sentence
metadata:
  version: 1.0
