tag:
  - base_tag_est
task: word_meanings_et
dataset_path: TalTechNLP/word_meanings_et
output_type: generate_until
validation_split: train
test_split: train
fewshot_split: train
process_docs: !function utils.process_docs
doc_to_text: "Sõna definitsioon(id): {{definition}}\nSõna:"
doc_to_target: word
num_fewshot: 3
metadata:
  version: 1.0
generation_kwargs:
  until:
    - "\n\n"
  max_gen_toks: 100
