tag:
  - custom_things
task: trivia_et_instr_gemma
dataset_path: TalTechNLP/trivia_et
output_type: multiple_choice
validation_split: train
test_split: train
fewshot_split: train
process_docs: !function utils.process_docs
doc_to_text: "Sa oled mälumängu ekspert. Su ülesanne on valida nelja vastusevariandi hulgast üks õige. Vasta ainult vastusega.\nKüsimus: {{küsimus}}\nVastusevariandid: {{vastusevariandid}}"
doc_to_target: vastus
doc_to_choice: vastusevariandid
num_fewshot: 0
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
