task: xcopa_et
dataset_path: cambridgeltl/xcopa
dataset_name: et
output_type: multiple_choice
validation_split: validation
test_split: test
doc_to_text: !function utils.doc_to_text_et
doc_to_target: label
doc_to_choice: !function utils.doc_to_choice
num_fewshot: 5
metric_list:
  - metric: acc
metadata:
  version: 1.0
