task: dialogsum_et_instr_gemma
dataset_path: TalTechNLP/dialogsum_ee
dataset_name: null
output_type: generate_until
generation_kwargs:
  until:
    - "\n\n"
  do_sample: false
  temperature: 0.0
training_split: null
validation_split: null
test_split: test
fewshot_split: null
doc_to_text: "Sa oled tehisintellekti ekspert eesti keele alal. Su ülesanne on analüüsida dialooge ja genereerida ühe või kahe lausega lühike kokkuvõte, mis kirjeldab dialoogi sisu. Ära unusta alati vastata eesti keeles. Vasta ainult kokkuvõttega!\nDialoog: {{dialogue}}"
doc_to_target: summary
num_fewshot: 0
should_decontaminate: false
doc_to_decontamination_query: sentence
metric_list:
  - metric: !function utils.rouge1
    higher_is_better: true
    aggregation: !function utils.rouge1_agg
  - metric: !function utils.rouge2
    higher_is_better: true
    aggregation: !function utils.rouge2_agg
  - metric: !function utils.rougeL
    higher_is_better: true
    aggregation: !function utils.rougeL_agg    
  - metric: !function utils.average_len
    higher_is_better: false
    aggregation: !function utils.average_len_agg
metadata:
  version: 1.0
