tag:
  - custom_things
task: grammar_et
dataset_path: TalTechNLP/grammar_et
output_type: generate_until
validation_split: train
test_split: train
fewshot_split: train
process_docs: !function utils.process_docs
doc_to_text: "Originaalne: {{original}}\nKorrektne:"
doc_to_target: correct
num_fewshot: 3
metadata:
  version: 1.0
generation_kwargs:
  until:
    - "\n\n"
  max_gen_toks: 100