tag:
  - custom_things
task: inflection_et_instr
dataset_path: TalTechNLP/inflection_et
output_type: generate_until
validation_split: train
test_split: train
fewshot_split: train
process_docs: !function utils.process_docs
doc_to_text: "ainsuse nimetav: {{noun_phrase}}\n{{plurality}} {{case}}:"
doc_to_target: inflection
num_fewshot: 5
metadata:
  version: 1.0
generation_kwargs:
  until:
    - "\n\n"
  max_gen_toks: 100